
meta_product_name: "Dive In Ocean"
meta_title: "Dive In Ocean - find the species you always wanted to dive with"
meta_description: "An interactive guide to where rare species have recently been spotted by divers"
meta_image: "cover.png" # should exist in `app/assets/images/
